# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy source and build
COPY tsconfig.json .
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Remove dev dependencies
RUN npm prune --production

# Default command
ENTRYPOINT ["node", "dist/index.js"]
